Omniship:
  debug: false
  track_timeout: 5

  UPS:
    username: '<%=ENV["UPS_USERNAME"]%>'
    password: '<%=ENV["UPS_PASSWORD"]%>'
    token: '<%=ENV["UPS_TOKEN"]%>'
    client_id: '<%=ENV["UPS_CLIENT_ID"]%>'
    client_secret: '<%=ENV["UPS_CLIENT_SECRET"]%>'
    test: false
    source: Wantable, Inc.

  USPS:
    client_ip: 127.0.0.1
    test: true

  Landmark:
    username: '<%=ENV["LANDMARK_USERNAME"]%>'
    password: '<%=ENV["LANDMARK_PASSWORD"]%>'
    client_id: '<%=ENV["LANDMARK_CLIENT_ID"]%>'
    test_mode: false

  DHLGM:
    username: '<%=ENV["DHLGM_USERNAME"]%>'
    password: '<%=ENV["DHLGM_PASSWORD"]%>'
    mailer_id: '<%=ENV["DHLGM_MAILER_ID"]%>'

  Newgistics:
    merchant_id: '<%=ENV["NEWGISTICS_MERCHANT_ID"]%>'
    api_key: '<%=ENV["NEWGISTICS_API_KEY"]%>'

  PitneyBowes:
    api_key: '<%=ENV["PITNEY_BOWES_API_KEY"]%>'
    api_secret: '<%=ENV["PITNEY_BOWES_API_SECRET"]%>'
    test: true

  FedEx:
    client_id: '<%=ENV["FEDEX_CLIENT_ID"]%>'
    client_secret: '<%=ENV["FEDEX_CLIENT_SECRET"]%>'
    test: true
